### ISSUE TITLE
Stars Badge

### ISSUE THREAD

**Issue by Mannuel25** [gaurtvin/python-projects#11]
The stars badge in the README keeps displaying Invalid. Tried fixing but all my effort proved baseless

**Comment by gaurtvin** [comment]
Ok! I'll am going to remove the star badge. Thanks for bringing my attention to that.

**Comment by Mannuel25** [comment]
> Ok! I'll am going to remove the star badge. Thanks for bringing my attention to that.

I guess it's working fine now :smile_cat:
