### ISSUE TITLE
Notimplementederror 

### ISSUE THREAD

**Issue by LeoLivs** [gaurtvin/Python-Projects#50]
Tried this on my mac and got a **_notimplementederror_**(no usable implementation found!) line 3, 79, 88

Also before that got a _**Modulenotfounderrror**_ no module names "pyobjus" line 93 

Searched and found this Link: https://www.educba.com/python-notimplementederror/

**Comment by gaurtvin** [comment]
Didn't get you, can you tell me what do you mean?

**Comment by LeoLivs** [comment]
I followed your instructions for this code on a Mac. (You said that you did it on windows and I got these errors when I applied this code to the terminal.

**Comment by gaurtvin** [comment]
Didn't get it yet, which project (specifically) you're asking. 

also, please attach screenshots.

**Comment by LeoLivs** [comment]
Apologies, I misread the readme.md. It clearly states that this code would not work with Mac,
